http:
  routers:
    app:
      rule: Host(`ateliware.localhost`)
      entryPoints:
        - web
      service: app
    mailpit:
      rule: Host(`mailpit.localhost`)
      entryPoints:
        - web
      service: mailpit
  services:
    app:
      loadBalancer:
        servers:
          - url: http://laravel.test:80
    mailpit:
      loadBalancer:
        servers:
          - url: http://mailpit:8025

tcp:
  routers:
    pgsql:
      rule: HostSNI(`*`)
      entryPoints:
        - pgsql
      service: pgsql
  services:
    pgsql:
      loadBalancer:
        servers:
          - address: pgsql:5432
